import Link from 'next/link';
import Hero from '../components/hero';
import Meta from '../components/meta';
import SidebarBanner from '../components/sidebar-banner';
import Layout from '../layout/layout';

const meta = {
  title: 'AI-powered API mocking',
  description:
    'Mockoon AI assistant helps you create realistic mock APIs in seconds for fast prototyping and learning'
};

const AIPoweredMocking = function () {
  return (
    <Layout footerBanner='download'>
      <Meta title={meta.title} description={meta.description} />

      <Hero
        title='🪄 <span class="text-primary">AI-powered</span> API mocking <span class="badge text-bg-warning fs-4 align-text-top ms-2">PRO</span>'
        subtitle='Mockoon AI assistant helps you create realistic mock APIs in seconds for fast prototyping and learning.'
      />

      <section className='py-6 py-md-8 border-top bg-gradient-light-white'>
        <div className='container'>
          <div className='row justify-content-center g-10'>
            <div className='col-12 col-lg-3'>
              <aside className='flex-grow-1 sticky-top pt-4'>
                <SidebarBanner
                  pro
                  title='Generate your own templates using AI'
                  text='With Mockoon Pro, you can unlock dozens of templates and
        generate your own using our AI assistant.'
                  link='/pro/'
                  ctaText='Discover Mockoon Pro →'
                />
              </aside>
            </div>
            <div className='col-12 col-lg-9'>
              <p>
                Mockoon Pro offers an <strong>AI assistant</strong> that can
                generate realistic mock APIs in seconds. It's a great way to
                quickly prototype an API or learn API development.
              </p>
              <p>
                <strong>Templates</strong> generated by the AI assistant are
                JSON templates that use our powerful{' '}
                <Link href='/docs/latest/templating/overview/'>
                  templating system
                </Link>{' '}
                to allow you to customize the API responses to your needs. You
                can directly copy-paste them into the body of your responses or
                into the content of a{' '}
                <Link href='/docs/latest/data-buckets/overview/'>
                  data bucket
                </Link>{' '}
                to simulate a database.
              </p>
              <p>
                Our AI assistant can be found in the{' '}
                <Link href={'/download/'}>desktop application</Link>. To
                generate a new template, click the "From template" button in the{' '}
                <strong>route creation menu</strong>. Then, click the "Generate"
                tab, write a prompt and click the "Generate" button. <br /> You
                can then copy-paste the template into the response's body or
                create a new GET endpoint or a{' '}
                <Link href={'/docs/latest/api-endpoints/crud-routes/'}>
                  CRUD endpoint
                </Link>{' '}
                with a data bucket.
              </p>
              <p className='text-center'>
                <img
                  src='/images/ai-powered-api-mocking/ai-generated-mock-api-endpoint.gif'
                  className='img-fluid mx-auto d-block mt-8 rounded'
                  alt='select generate from template in the route creation menu to create a AI-generated mock API endpoint'
                  width='766'
                  height='605'
                />
              </p>
            </div>
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default AIPoweredMocking;
